#LET'S JUMP IT
# THIS IS A FIRST TRY HOW TO AVOID SINGLE LINES COMMENT.
Var = """OKAY HOW TO AVOID MULTI LINES COMMENT \n"
 "ITS SHOW'S ERROR\n"
 "THEN TRY THE FORMULA ONCE \n"
 "LETS START\n"
 "ARE YOU READY\n"
 "LETS DO THIS \n"
 "OK DONE """
# NOW PRINTS MY LINES
print("THIS IS A FIRST PROJECT IN PYTHON, (MINE) \n")
print("PLEASE DON'T SHOW ANY ERROR OR,\n")
print("POP-UP", end=".")
# OKAY.RUN THIS CODE AND FIXED THE BUGS,IF THERE ARE ANY BUGS.
